### PR TITLE
resolves compilation error caused by 97460af

### PR DESCRIPTION
**Pull request by uabassguy**
specify type in phpdoc resolves error during compilation

### CODE REVIEW

**Comment by uabassguy** [comment]
Not sure why CI build failed, I just changed a phpdoc, possibly a concurrent build caused a failure? Please advise. I have already resolved it on my end but others are going to have issues if they deploy before this can be merged.

**Comment by vvuksan** [comment]
Thanks for the fix.

**Comment by vvuksan** [comment]
Fix released in 1.2.106

**Comment by uabassguy** [comment]
Thanks for the quick merge
